services:
  api:
    build: .
    container_name: vmp-api
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/vmp
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=local_dev_secret_change_me
      - CORS_ORIGINS=*
    depends_on:
      - mongo
      - redis
    command: ["node", "dist/main.js"]

  mongo:
    image: mongo:7
    container_name: vmp-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: vmp-redis
    ports:
      - "6379:6379"

  mongo-express:
    image: mongo-express:1.0.2-20
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

volumes:
  mongo-data:
